config/routes.rb
Rails.application.routes.draw do


  root 'pages#index'
  get 'pages/help'

  get 'sessions/new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :topics

  get 'favorites/index'
  post '/favorites' => 'favorites#create'
  delete '/favorites' => 'favorites#destroy'

  get '/comments' => 'comments#new'
  post '/comments' => 'comments#create'
  delete '/comments' => 'comments#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :user_id, presence: true
  validates :topic_id, presence: true
  validates :content, presence: true, length: {maximum: 50}
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  EMAIL_REGULAR = /\A([^@\s]+)@[a-zA-Z0-9]+\.[a-zA-Z0-9-\.]+\z/
  PASS_REGULAR = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)[a-zA-Z\d]{8,32}+\z/

  validates :name, presence: true, length: {maximum: 15}
  validates :email, presence: true, uniqueness: true, format: {with: EMAIL_REGULAR}
  validates :password, presence: true, format: {with: PASS_REGULAR}

  has_secure_password

  has_many :topics
  has_many :favorites
  # ↓は任意のuserはfavoriteを持っていて、それを通して（favoriteの中のtopic_id）topicを持つ
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :success, :info, :warning, :danger

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    # !はfalseとtrueを入れ替える（つまりcurrent_userがいるときにtrue）
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @topic_id = params[:topic_id]
  end

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to topic_path(id: @comment.topic_id)
    else
      redirect_to topic_path(id: params[:topic_id]), danger: "コメントを送信できません"
    end
  end

  def destroy
    comment = Comment.find(params[:comment_id]).destroy
    redirect_to topic_path(id: comment.topic_id), info: "コメントを削除しました"
  end

  private
  def comment_params
    params.require(:comment).permit(:topic_id, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favote_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]
    if favorite.save
      redirect_to topics_path
    else
      redirect_to topics_path, danger: 'いいねできません'
    end
  end

  def destroy
    favorite = Favorite.find_by(topic_id: params[:topic_id], user_id: current_user.id)
    favorite.destroy
    redirect_to topics_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインできません'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: 'ログアウトしました'
  end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # session_paramsに移し替えるイメージ
  def session_params
   params.permit(:email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all.order(id: "DESC").includes(:favorite_users)
  end

  def show
    @topic = Topic.find(params[:id])
    @comments = Comment.where(topic_id: params[:id])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_parems)

    if @topic.save
      redirect_to topics_path, succes: '投稿しました'
    else
      flash.now[:danger] = "投稿できません"
      render :new
    end
  end

  private
  def topic_parems
    params.require(:topic).permit(:image, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    # binding.pry
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録完了'
    else
      flash.now[:danger] = '登録失敗'
      render :new
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Comment</h1>
        <% if logged_in? %>
          <%= form_with model: @comment do |f| %>
            <div class="form-group">
              <%= f.label :content %>
              <%= f.text_area :content, class: 'form-control' %>

              <%= f.hidden_field :topic_id, :value => @topic_id %>
            </div>
            <%= f.submit 'コメントする', class: 'btn btn-black btn-block' %>
          <% end %>
        <% else %>
          <h1>ログインしてください</h1>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert">
        <%= value %>
      </div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <%end%>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
                <a href="/topics">投稿一覧</a>
            </li>
            <li>
              <%= link_to favorites_index_path do %>
                <% image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <% image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <% image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <% image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <% image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>

    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページですよ</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Pictgram</h1>
    <h2 class="text-white">Pictgramはあなたの投稿を待っています</h2>
    <h2 class="text-white">確認用テスト</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to '新規登録', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%=link_to 'ログイン', 'login_path', class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user)%>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
              <% end %>

            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <%= image_tag 'icons/heart.png', class: 'topic-index-icon heart-red' %>
              <% end %>
            <% end %>
            <%= topic.favorites.count%>
            <%= link_to comments_path(topic_id: topic.id), method: :get do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <%= link_to topic_path(id: topic.id) do %>
              <p><%= topic.comments.count %>件のコメント</p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <% if logged_in? %>
          <%= form_with model: @topic do |f| %>
            <div class="form-group">
              <%= f.label :image %>
              <%= f.file_field :image%>
            </div>
            <div class="form-group">
              <%= f.label :description %>
              <%= f.text_area :description, class: 'form-control' %>
            </div>
            <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        <% else %>
          <h1>ログインしてください</h1>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="topic-index-single">
          <h2 class="topic-author">
            <%= @topic.user.name %>
          </h2>
          <%= image_tag @topic.image.url %>

          <% if !@topic.favorite_users.include?(current_user)%>
            <%= link_to favorites_path(topic_id: @topic.id), method: :post do %>
              <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
            <% end %>

          <% else %>
            <%= link_to favorites_path(topic_id: @topic.id), method: :delete do %>
              <%= image_tag 'icons/heart.png', class: 'topic-index-icon heart-red' %>
            <% end %>
          <% end %>
          <%= @topic.favorites.count %>
          <%= link_to comments_path(topic_id: @topic.id), method: :get do %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <%= @topic.comments.count %>
          <% end %>
          <p class="topic-text">
            <%= @topic.description %>
          </p>
          <p class="comment-title">コメント</p>
         <% @comments.each do |comment| %>
           <div>
             <%= comment.user.name %>
           </div>
           <div class="comment-sentence">
             <%= comment.content %>
           </div>
           <% if comment.user_id = current_user.id %>
             <%= link_to "削除", comments_path(comment_id: comment.id), class: 'btn', method: :delete %>
           <% end %>
         <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">新規登録</h1>
        <%= form_with model: @user, local: true do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confrimation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', '#', class: 'text-white' %>
      </div>
    </div>
  </div>
</div>